"""Pydantic models for skill I/O — structured LLM responses."""

from typing import List, Optional

from pydantic import BaseModel, Field


class GeneratedQuery(BaseModel):
    """A single YouTube search query generated by StrategyGeneration skill."""
    query: str
    strategy_name: str
    bilibili_check: str = ""
    target_channels: List[str] = Field(default_factory=list)
    reasoning: str = ""


class NewStrategyProposal(BaseModel):
    """A proposal for a new discovery strategy."""
    name: str
    description: str
    youtube_tactics: str = ""
    example_queries: List[str] = Field(default_factory=list)
    target_channels: List[str] = Field(default_factory=list)
    bilibili_check: str = ""
    reasoning: str = ""


class StrategyGenerationOutput(BaseModel):
    """Full output from the StrategyGeneration skill."""
    queries: List[GeneratedQuery] = Field(default_factory=list)
    new_strategy_proposals: List[NewStrategyProposal] = Field(default_factory=list)
    retire_suggestions: List[str] = Field(default_factory=list)


class MarketAssessment(BaseModel):
    """Market analysis output for a Bilibili content niche."""
    is_saturated: bool = False
    opportunity_score: float = Field(default=0.5, ge=0.0, le=1.0)
    quality_gap: str = "medium"
    freshness_gap: str = "medium"
    reasoning: str = ""
    suggested_angle: str = ""


class YieldReflectionOutput(BaseModel):
    """Output from Loop 1 yield reflection (StrategyGeneration)."""
    updated_youtube_principles: str = ""
    new_strategies: List[NewStrategyProposal] = Field(default_factory=list)
    channels_to_follow: List[dict] = Field(default_factory=list)
    retire: List[str] = Field(default_factory=list)
    analysis: str = ""


class OutcomeReflectionOutput(BaseModel):
    """Output from Loop 2 outcome reflection (StrategyGeneration)."""
    updated_bilibili_principles: str = ""
    scoring_insights: str = ""
    analysis: str = ""


class MarketReflectionOutput(BaseModel):
    """Output from Loop 2 reflection (MarketAnalysis)."""
    updated_criteria: str = ""
    threshold_adjustments: str = ""
    analysis: str = ""


class TransportabilityCheck(BaseModel):
    """LLM transportability check result."""
    transportable: bool = True
    reasoning: str = ""
