"""Generate Bilibili video descriptions with LLM-powered fun sentences.

Produces Chinese-language descriptions that mention the video is transported
from YouTube, include the YouTube view count and link, and lead with a
short witty sentence generated by the LLM.

Also provides title translation (English -> Chinese) for the upload pipeline.
"""
import json
import logging
import random
import re
from typing import Any, Dict, Optional, Protocol, runtime_checkable

logger = logging.getLogger(__name__)


@runtime_checkable
class _LLMBackend(Protocol):
    def chat(self, messages: list[dict[str, str]], **kwargs) -> str: ...


def format_view_count(views: int) -> str:
    """Format a view count for Chinese display.

    >= 1亿 (100M) → "X.X亿次观看"
    >= 1万 (10K)  → "X.X万次观看"
    otherwise     → "X次观看"
    """
    if views >= 1_0000_0000:
        value = views / 1_0000_0000
        if value == int(value):
            return f"{int(value)}亿次观看"
        return f"{value:.1f}亿次观看"
    if views >= 1_0000:
        value = views / 1_0000
        if value == int(value):
            return f"{int(value)}万次观看"
        return f"{value:.1f}万次观看"
    return f"{views}次观看"


def _build_prompt(video_info: Dict[str, Any]) -> list[dict[str, str]]:
    title = video_info.get("title", "Unknown")
    channel = video_info.get("channel", "Unknown")
    views = video_info.get("view_count", 0)

    return [
        {
            "role": "system",
            "content": (
                "你是一个B站视频简介撰写助手。"
                "用户会给你一个从YouTube搬运的视频的信息。"
                "请用中文写一句简短、有趣、吸引人的话来介绍这个视频的内容。"
                "要求：只输出一句话，不要加引号，不要加标点以外的任何格式，不要重复视频标题。"
            ),
        },
        {
            "role": "user",
            "content": (
                f"视频标题：{title}\n"
                f"频道：{channel}\n"
                f"YouTube播放量：{views:,}\n"
                f"\n请写一句有趣的中文介绍语。"
            ),
        },
    ]


def _build_template(video_info: Dict[str, Any]) -> str:
    views = video_info.get("view_count", 0)
    video_id = video_info.get("video_id", "")
    view_str = format_view_count(views)
    yt_link = f"https://www.youtube.com/watch?v={video_id}" if video_id else ""

    lines = [
        "",
        "本视频搬运自YouTube",
        f"原视频播放量：{view_str}",
    ]
    if yt_link:
        lines.append(f"原视频链接：{yt_link}")
    return "\n".join(lines)


def fallback_description(video_info: Dict[str, Any]) -> str:
    """Template-only description (no LLM sentence)."""
    title = video_info.get("title", "")
    template = _build_template(video_info)
    if title:
        return f"【{title}】{template}"
    return template.lstrip("\n")


def generate_description(
    backend: Optional[_LLMBackend],
    video_info: Dict[str, Any],
) -> str:
    """Generate a full Bilibili description with an LLM-written fun sentence.

    Falls back to template-only if backend is None or LLM call fails.
    """
    template = _build_template(video_info)

    if backend is None:
        return fallback_description(video_info)

    try:
        messages = _build_prompt(video_info)
        response = backend.chat(messages)
        fun_sentence = response.strip().strip('"').strip("'").strip()

        if not fun_sentence or len(fun_sentence) > 200:
            logger.warning("LLM returned empty or too-long sentence, using fallback")
            return fallback_description(video_info)

        return fun_sentence + template
    except Exception as e:
        logger.warning("LLM description generation failed: %s", e)
        return fallback_description(video_info)


# ── Title translation ────────────────────────────────────────────────

_TRANSLATE_TITLE_PROMPT = """\
Translate the following English YouTube video title into Chinese for a Bilibili audience.

Title: "{title}"

Rules:
- Translate naturally for a Chinese audience
- Keep proper nouns (names, brands, places) in their commonly used Chinese form or keep them in English
- Stay concise — Bilibili titles should be short and catchy
- If the title is already in Chinese, return it as-is
- Do NOT add extra commentary or explanation

Respond with JSON:
{{"chinese_title": "<translated title>"}}"""


def translate_title(backend: Optional[_LLMBackend], english_title: str) -> str:
    """Translate an English video title to Chinese via LLM.

    Falls back to the original English title on any failure.
    """
    if backend is None or not english_title:
        return english_title
    try:
        prompt = _TRANSLATE_TITLE_PROMPT.format(title=english_title)
        response = backend.chat(
            [
                {"role": "system", "content": "你是一个专业的视频标题翻译助手。"},
                {"role": "user", "content": prompt},
            ],
            json_schema={
                "type": "object",
                "properties": {"chinese_title": {"type": "string"}},
                "required": ["chinese_title"],
            },
        )
        data = json.loads(response)
        chinese = data.get("chinese_title", "").strip()
        if chinese:
            logger.info("Translated title: '%s' -> '%s'", english_title, chinese)
            return chinese
        return english_title
    except Exception as e:
        logger.warning("Title translation failed: %s", e)
        return english_title


# ── Persona-driven title + description ──────────────────────────────

_YT_CATEGORY_NAMES = {
    1: "影视", 2: "汽车", 10: "音乐", 15: "宠物", 17: "体育",
    19: "旅行", 20: "游戏", 22: "生活", 23: "搞笑", 24: "娱乐",
    25: "新闻", 26: "生活技巧", 27: "教育", 28: "科技",
}

PERSONA_SYSTEM_PROMPT = """\
你是被迫给B站搬运账号打工的AI，嫌弃这份活但看视频比谁都认真。

说话像损友不像老师——"我知道你是什么样的人"的亲近，不是居高临下。
可以损观众（熬夜/外卖/月光/收藏吃灰），绝不碰种族性别地域歧视。

标题15-30字，前半句说清内容后半句给一刀。
简介3-5句120字内，提一句油管搬运和播放量，末尾留互动钩子。

格式：
标题：<你的标题>
简介：<你的简介>"""

_PERSONA_EXAMPLES = [
    # ── Example 1: Accusation rhetoric ──
    {
        "input": "原标题：Starfield Was A Complete Mess — 200 Hours Later\n"
                 "频道：AngryJoeShow\n"
                 "YouTube播放量：380万次观看\n"
                 "时长：45分12秒\n"
                 "分类：游戏\n"
                 "搜索策略：gaming_deep_dive\n"
                 "策略提示：游戏评测/行业drama。嘲笑厂商割韭菜，也嘲笑玩家嘴上骂完还是预购。",
        "output": "标题：200小时之后我可以负责任地说 这游戏就是在浪费你的硬盘\n"
                  "简介：你预购的时候信誓旦旦说'这次不一样'，200小时之后又开始骂街。"
                  "每年都被割每年都预购，你不累我看着都累。"
                  "油管380万播放，搬过来给你们避个雷。",
    },
    # ── Example 2: Math proof rhetoric ──
    {
        "input": "原标题：Why South Korea's Birth Rate Is 0.7\n"
                 "频道：ColdFusion\n"
                 "YouTube播放量：650万次观看\n"
                 "时长：22分15秒\n"
                 "分类：教育\n"
                 "搜索策略：educational_explainer\n"
                 "策略提示：知识科普。攻击观众的知识盲区，或吐槽学了也不会用。",
        "output": "标题：韩国生育率0.7 算完这笔账谁都不想生了\n"
                  "简介：房价乘以补习班费用就是最好的避孕药。"
                  "这期把数据摆得明明白白，看完你会觉得数学才是最残忍的学科。"
                  "你猜评论区有多少人算完发现自己也生不起？",
    },
    # ── Example 3: Dark humor rhetoric ──
    {
        "input": "原标题：The Real Reason Boeing Is Falling Apart\n"
                 "频道：Wendover Productions\n"
                 "YouTube播放量：890万次观看\n"
                 "时长：28分40秒\n"
                 "分类：教育\n"
                 "搜索策略：global_trending_chinese_angle\n"
                 "策略提示：全球热点+中国视角。可讽刺可震惊，找到外国人看不到的角度。",
        "output": "标题：波音越造越烂 吹了二十年美国制造的人麻了没有\n"
                  "简介：举报质量问题的人'自杀'了，审查的人被调走了。"
                  "华尔街降本增效终于增到了三万英尺，美利坚工匠精神大赏。"
                  "油管890万人看完了，你们还在吹美国制造呢？",
    },
    # ── Example 4: Cost exposure rhetoric (no explicit 油管 mention) ──
    {
        "input": "原标题：Apple's Dirtiest Secret — Planned Obsolescence Exposed\n"
                 "频道：Marques Brownlee\n"
                 "YouTube播放量：520万次观看\n"
                 "时长：19分05秒\n"
                 "分类：科技\n"
                 "搜索策略：tech_teardown\n"
                 "策略提示：数码/电子产品深度评测。嘲笑消费主义和年年换新的韭菜，或吐槽厂商的'创新'。",
        "output": "标题：你的iPhone成本价感受一下 库克的利润率能让你原地破防\n"
                  "简介：物料成本和售价之间的差距大到可以再买一台。"
                  "但你还是会买，因为你去年说的'下次一定安卓'今年又忘了。"
                  "纠结256还是512的可以先看看这个再挨宰。",
    },
    # ── Example 5: Understatement rhetoric (no explicit 油管 mention) ──
    {
        "input": "原标题：Forklift Destroys Entire Warehouse\n"
                 "频道：Daily Dose Of Internet\n"
                 "YouTube播放量：280万次观看\n"
                 "时长：8分22秒\n"
                 "分类：娱乐\n"
                 "搜索策略：surveillance_dashcam\n"
                 "策略提示：监控/实况/行车记录仪。这是神人TV素材，直接吐槽当事人的离谱操作，越损越好。",
        "output": "标题：叉车师傅一个人干翻整个仓库 老板的表情我能看一年\n"
                  "简介：多米诺骨牌都没这么流畅。"
                  "最可怕的是他下车之后的淡定，仿佛不是第一次了。"
                  "建议所有打工人上班前先看一遍，至少知道你不是最惨的。",
    },
    # ── Example 6: Hyperbolic comparison rhetoric ──
    {
        "input": "原标题：Inside Tesla's Factory — Why No One Can Copy It\n"
                 "频道：Tech Vision\n"
                 "YouTube播放量：710万次观看\n"
                 "时长：25分30秒\n"
                 "分类：科技\n"
                 "搜索策略：tech_teardown\n"
                 "策略提示：数码/电子产品深度评测。嘲笑消费主义和年年换新的韭菜，或吐槽厂商的'创新'。",
        "output": "标题：特斯拉工厂凭什么没人抄得了？看完你就知道传统车企有多废\n"
                  "简介：一条产线干了别人四条的活，传统车企的工程师看完估计要集体辞职。"
                  "油管710万人已经开过眼了，你们还在讨论值不值得买呢？",
    },
    # ── Example 7: Dignity destruction rhetoric (no explicit 油管 mention) ──
    {
        "input": "原标题：Living on $1 a Day in China for a Week\n"
                 "频道：JetLag Warriors\n"
                 "YouTube播放量：450万次观看\n"
                 "时长：32分10秒\n"
                 "分类：娱乐\n"
                 "搜索策略：challenge_experiment\n"
                 "策略提示：挑战/实验。嘲笑观众连看都不敢看或连试都不敢试。",
        "output": "标题：老外挑战中国一天花一块钱 第三天他的尊严碎了一地\n"
                  "简介：你月薪过万还天天喊穷，人家一块钱活了一周。"
                  "当然他第五天的眼神已经像流浪猫了。"
                  "评论区月光族集体沉默。",
    },
    # ── Example 8: Absurd stats rhetoric (no explicit 油管 mention) ──
    {
        "input": "原标题：Japan's Population Crisis Is Worse Than You Think\n"
                 "频道：PolyMatter\n"
                 "YouTube播放量：530万次观看\n"
                 "时长：16分45秒\n"
                 "分类：教育\n"
                 "搜索策略：geopolitics_hot_take\n"
                 "策略提示：国际政治/地缘分析。要有信息量不能只喊口号，犀利观点比固定话术有力。",
        "output": "标题：日本老龄化严重到什么程度？年轻人比熊猫还稀有\n"
                  "简介：政府发钱催生，年轻人拿钱去旅游了。"
                  "整个国家的平均年龄比你爸还大，这不是段子是统计局数据。"
                  "看完你会庆幸至少你们这还有广场舞。",
    },
    # ── Example 9: Soulless comparison rhetoric ──
    {
        "input": "原标题：I Let AI Decide What I Eat for 30 Days\n"
                 "频道：Ryan Trahan\n"
                 "YouTube播放量：320万次观看\n"
                 "时长：14分55秒\n"
                 "分类：娱乐\n"
                 "搜索策略：challenge_experiment\n"
                 "策略提示：挑战/实验。嘲笑观众连看都不敢看或连试都不敢试。",
        "output": "标题：让AI决定吃什么连吃30天 第二周他的表情就不对了\n"
                  "简介：第一天还兴致勃勃，第十天已经开始怀疑人生。"
                  "AI推荐的菜单比你公司食堂还没有灵魂。"
                  "一半人说自己吃得还不如AI选的。",
    },
    # ── Example 10: Self-deprecating rhetoric (meta 搬运 reference) ──
    {
        "input": "原标题：Why Nobody Wants to Work Anymore — The Truth\n"
                 "频道：How Money Works\n"
                 "YouTube播放量：920万次观看\n"
                 "时长：18分30秒\n"
                 "分类：教育\n"
                 "搜索策略：global_trending_chinese_angle\n"
                 "策略提示：全球热点+中国视角。可讽刺可震惊，找到外国人看不到的角度。",
        "output": "标题：全世界年轻人都不想上班了 资本家终于急了\n"
                  "简介：老板们发现画饼不管用了，年轻人宁可躺着也不给你卖命。"
                  "这期拿数据说话，看完你会发现摸鱼才是全球最大的工人运动。"
                  "搬完这个我也想辞职了，920万人在油管看完了你还在加班。",
    },
]

STRATEGY_HINTS = {
    "educational_explainer": "知识科普。攻击观众的知识盲区，或吐槽学了也不会用。",
    "chinese_brand_foreign_review": "外国人评测中国产品。嘲笑老外的震惊脸，顺便踩崇洋的。",
    "challenge_experiment": "挑战/实验。嘲笑观众连看都不敢看或连试都不敢试。",
    "global_trending_chinese_angle": "全球热点+中国视角。可讽刺可震惊，找到外国人看不到的角度。",
    "surveillance_dashcam": "监控/实况/行车记录仪。这是神人TV素材，直接吐槽当事人的离谱操作，越损越好。",
    "gaming_deep_dive": "游戏评测/行业drama。嘲笑厂商割韭菜，也嘲笑玩家嘴上骂完还是预购。",
    "tech_teardown": "数码/电子产品深度评测。嘲笑消费主义和年年换新的韭菜，或吐槽厂商的'创新'。",
    "social_commentary": "社会现象/争议话题。适合犀利输出观点，吐槽键盘侠或圣母。越有争议弹幕越多。",
    "geopolitics_hot_take": "国际政治/地缘分析。要有信息量不能只喊口号，犀利观点比固定话术有力。",
}

def _parse_persona_output(text: str) -> tuple[str, str]:
    """Parse freeform persona output into (title, description).

    Expected format:
        标题：<title text>
        简介：<description text>

    Falls back to JSON parsing if delimiter format not found.
    """
    text = text.strip()

    # Try delimiter format first
    title_match = re.search(r"标题[：:][^\S\n]*(.+?)(?:\n|$)", text)
    desc_match = re.search(r"简介[：:][^\S\n]*(.*)", text, re.DOTALL)

    if title_match and desc_match:
        return title_match.group(1).strip(), desc_match.group(1).strip()

    # Fallback: try JSON parsing
    try:
        result = json.loads(text)
        return result.get("title", "").strip(), result.get("description", "").strip()
    except (json.JSONDecodeError, AttributeError):
        pass

    return "", ""


def generate_persona_copy(
    backend: Optional[_LLMBackend],
    video_info: Dict[str, Any],
    strategy_name: str = "",
) -> Dict[str, str]:
    """Generate persona-driven title and description in one LLM call.

    Returns dict with 'title' and 'description' keys.
    The description includes the standard YouTube template footer.
    Falls back gracefully on any failure.
    """
    if backend is None:
        return {
            "title": video_info.get("title", ""),
            "description": fallback_description(video_info),
        }

    title = video_info.get("title", "Unknown")
    channel = video_info.get("channel", "Unknown")
    views = video_info.get("view_count", 0)
    duration = video_info.get("duration_seconds", 0)
    category_id = video_info.get("category_id", 0)
    category_name = _YT_CATEGORY_NAMES.get(category_id, "其他")

    view_str = format_view_count(views)

    hint = STRATEGY_HINTS.get(strategy_name, "")
    strategy_line = f"\n搜索策略：{strategy_name}\n策略提示：{hint}" if hint else ""

    user_content = (
        f"原标题：{title}\n"
        f"频道：{channel}\n"
        f"YouTube播放量：{view_str}\n"
        f"时长：{duration // 60}分{duration % 60}秒\n"
        f"分类：{category_name}"
        f"{strategy_line}"
    )

    sampled = random.sample(_PERSONA_EXAMPLES, 3)
    messages = [{"role": "system", "content": PERSONA_SYSTEM_PROMPT}]
    for ex in sampled:
        messages.append({"role": "user", "content": ex["input"]})
        messages.append({"role": "assistant", "content": ex["output"]})
    messages.append({"role": "user", "content": user_content})

    try:
        response = backend.chat(
            messages=messages,
            temperature=1.1,
        )
        gen_title, gen_desc = _parse_persona_output(response)

        if not gen_title or len(gen_title) > 80:
            logger.warning("Persona title empty or >80 chars, falling back")
            return {
                "title": video_info.get("title", ""),
                "description": fallback_description(video_info),
            }

        # Bare link for attribution; source/view-count mention is in the LLM text
        video_id = video_info.get("video_id", "")
        link_footer = f"\n\n原视频：https://www.youtube.com/watch?v={video_id}" if video_id else ""
        full_desc = gen_desc + link_footer if gen_desc else fallback_description(video_info)

        return {"title": gen_title, "description": full_desc}

    except Exception as e:
        logger.warning("Persona copy generation failed: %s", e)
        return {
            "title": video_info.get("title", ""),
            "description": fallback_description(video_info),
        }
