"""LLM-driven topic and query generation for YouTube discovery.

Uses transport strategies + Bilibili hot words + past successes to generate
targeted YouTube search queries through an LLM.
"""
import logging
from typing import Optional

from pydantic import BaseModel

from ..llm.backend import LLMBackend
from .strategies import TransportStrategy

logger = logging.getLogger(__name__)


class GeneratedQuery(BaseModel):
    """A YouTube search query generated by the LLM."""
    query: str
    strategy_name: str
    bilibili_check: str  # Chinese equivalent for saturation check
    reasoning: str


class QueryGenerationResult(BaseModel):
    """Result from the LLM query generation."""
    queries: list[GeneratedQuery]


TOPIC_GENERATION_SYSTEM = (
    "You are an expert at finding YouTube videos that will perform well when "
    "transported (re-uploaded with Chinese subtitles) to Bilibili. "
    "You understand which YouTube content resonates with Chinese audiences. "
    "Respond in the exact JSON format requested."
)

TOPIC_GENERATION_PROMPT = """\
Generate YouTube search queries to find videos suitable for transporting to Bilibili.

## Available Transport Strategies (sorted by opportunity — least saturated first)
{strategies_text}

## Current Bilibili Hot Words (audience demand signals)
{hot_words_text}

## Past Successful Transports (for reference)
{past_successes_text}

## Task
For each unsaturated strategy, generate 2-3 specific YouTube search queries that:
1. Combine the strategy angle with current demand signals (hot words)
2. Target content that doesn't already exist on Bilibili
3. Are specific enough to find high-quality results
4. Are in English (for YouTube search)

Also provide a Chinese equivalent (bilibili_check) for each query so we can verify
the content doesn't already exist on Bilibili.

Respond with JSON:
{{
  "queries": [
    {{
      "query": "<English YouTube search query>",
      "strategy_name": "<which strategy this targets>",
      "bilibili_check": "<Chinese search term to check Bilibili saturation>",
      "reasoning": "<why this query is promising>"
    }}
  ]
}}

Generate 10-20 queries total, focusing on the least saturated strategies."""


REFINE_PROMPT = """\
The following queries were found to be saturated on Bilibili (similar content already exists):

{saturated_queries}

Generate alternative, more specific queries for the same strategies.
Find narrower angles or more recent topics that haven't been covered yet.

Respond with the same JSON format:
{{
  "queries": [
    {{
      "query": "<English YouTube search query>",
      "strategy_name": "<strategy>",
      "bilibili_check": "<Chinese check term>",
      "reasoning": "<why this is different/better>"
    }}
  ]
}}"""


class TopicGenerator:
    """Generates YouTube search queries using LLM + strategy context."""

    def __init__(self, backend: LLMBackend):
        self._backend = backend

    def generate_queries(
        self,
        strategies: list[TransportStrategy],
        hot_words: list[dict],
        past_successes: list[dict],
    ) -> list[GeneratedQuery]:
        """Generate YouTube search queries from strategies + demand signals.

        Args:
            strategies: Transport strategies sorted by saturation (least first).
            hot_words: List of {"keyword": str, "heat_score": int} dicts.
            past_successes: List of {"title": str, "views": int} dicts from VectorStore.

        Returns:
            List of GeneratedQuery objects.
        """
        strategies_text = self._format_strategies(strategies)
        hot_words_text = self._format_hot_words(hot_words)
        past_text = self._format_past_successes(past_successes)

        prompt = TOPIC_GENERATION_PROMPT.format(
            strategies_text=strategies_text,
            hot_words_text=hot_words_text,
            past_successes_text=past_text,
        )

        try:
            content = self._backend.chat(
                messages=[
                    {"role": "system", "content": TOPIC_GENERATION_SYSTEM},
                    {"role": "user", "content": prompt},
                ],
                json_schema=QueryGenerationResult.model_json_schema(),
            )

            result = QueryGenerationResult.model_validate_json(content)

            # Filter out empty queries
            queries = [q for q in result.queries if q.query.strip()]

            logger.info("LLM generated %d search queries", len(queries))
            return queries

        except Exception as e:
            logger.error("Query generation failed: %s", e)
            return []

    def refine_queries(
        self,
        saturated_queries: list[GeneratedQuery],
    ) -> list[GeneratedQuery]:
        """Generate alternative queries for saturated topics.

        Args:
            saturated_queries: Queries whose content already exists on Bilibili.

        Returns:
            New, more specific queries.
        """
        if not saturated_queries:
            return []

        saturated_text = "\n".join(
            f"- [{q.strategy_name}] \"{q.query}\" — {q.reasoning}"
            for q in saturated_queries
        )

        prompt = REFINE_PROMPT.format(saturated_queries=saturated_text)

        try:
            content = self._backend.chat(
                messages=[
                    {"role": "system", "content": TOPIC_GENERATION_SYSTEM},
                    {"role": "user", "content": prompt},
                ],
                json_schema=QueryGenerationResult.model_json_schema(),
            )

            result = QueryGenerationResult.model_validate_json(content)
            queries = [q for q in result.queries if q.query.strip()]

            logger.info("LLM refined %d queries into %d alternatives",
                        len(saturated_queries), len(queries))
            return queries

        except Exception as e:
            logger.error("Query refinement failed: %s", e)
            return []

    def _format_strategies(self, strategies: list[TransportStrategy]) -> str:
        lines = []
        for s in strategies:
            sat_label = "LOW" if s.saturation_score < 0.5 else (
                "MEDIUM" if s.saturation_score < 1.0 else "HIGH"
            )
            lines.append(
                f"- **{s.name}** [Saturation: {sat_label} ({s.saturation_score:.1f})]\n"
                f"  {s.description}\n"
                f"  Example queries: {', '.join(s.example_queries)}"
            )
        return "\n".join(lines) if lines else "No strategies available."

    def _format_hot_words(self, hot_words: list[dict]) -> str:
        if not hot_words:
            return "No hot words available."
        lines = []
        for hw in hot_words[:15]:
            lines.append(f"- {hw['keyword']} (heat: {hw['heat_score']:,})")
        return "\n".join(lines)

    def _format_past_successes(self, past_successes: list[dict]) -> str:
        if not past_successes:
            return "No past transport data available."
        lines = []
        for ps in past_successes[:10]:
            lines.append(f"- \"{ps['title']}\" — {ps['views']:,} views")
        return "\n".join(lines)
